config/routes.rb
TestHp::Application.routes.draw do
  get "rating/end_page"

  get "rating/final_rating"

  get "rating/rating_page"

  resources :participants
  get "home/index"
  get "rating/rating_page"

  root :to => 'home#index'

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :date, :time, :sres1, :sres2, :sres3, :sres4, :sres5, :sres6, :sres_final, :comment, :id
  
  #validates :date, :presence => true
  #validates :time, :presence => true
  #validates :res1, :presence => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:cmd_nr] = 1;
    session[:cmd_order] = [1,2,3,4,5,6].shuffle
  end  
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  http_basic_authenticate_with :name => "bheinric", :password => "warumrappstdu" , :except => [:new, :create, :update]
  
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new
    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
   @participant = Participant.find(session[:id])
   #@participant[:res2] = 'qw'

    respond_to do |format|
      if @participant.save and session[:cmd_nr] < 6
        session[:cmd_nr]+=1
        format.html { redirect_to :back}
        #format.json { render json: @participant, status: :created, location: @participant }
      elsif @participant.save and session[:cmd_nr] == 6
        session[:cmd_nr]+=1
        format.html { redirect_to "/rating/final_rating" }
      elsif @participant.save and session[:cmd_nr] == 7
        format.html { redirect_to "/rating/end_page" }
        #format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
  #  @participant = Participant.find(session[:id])
    
   @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant]) and session[:cmd_nr] < 6
        session[:cmd_nr]+=1
        format.html { redirect_to :back }
        #format.json { head :no_content }
      elsif @participant.update_attributes(params[:participant]) and session[:cmd_nr] == 6
        session[:cmd_nr]+=1
        format.html { redirect_to "/rating/final_rating" }
      elsif @participant.update_attributes(params[:participant]) and session[:cmd_nr] == 7
        format.html { redirect_to "/rating/end_page" }
      #else
        #format.html { render action: "edit" }
        #format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      #format.json { head :no_content }
    end
  end
end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  
  def rating_page
    if session[:cmd_nr] == 1
      @participant = Participant.create(params[:participant])
    else 
      @participant = Participant.find(session[:id])
    end
    session[:id] = @participant[:id]
    
    #@cmd_nr = 1
    #@com = [1,2,3,4,5]
    #@ind_titel = ['A','B','C','D','E']
    @ind_titel = [1,2,3,4,5]
    @assign = Hash[@ind_titel.map {|x| [x, nil]}]      
    a00wf000_cmd = ['a00wf000', 'a00wf000_90', 'a00wf000_115', 'a00wf000_80to120_lin', 'a00wf000_S3_80to120_binary']
    a00wf000_cmd = a00wf000_cmd.shuffle
    bl0a0b00_cmd = ['bl0a0b00', 'bl0a0b00_90', 'bl0a0b00_115', 'bl0a0b00_80to120_lin', 'bl0a0b00_S3_80to120_binary']
    bl0a0b00_cmd = bl0a0b00_cmd.shuffle
    bl0c0z00_cmd = ['bl0c0z00', 'bl0c0z00_90', 'bl0c0z00_115', 'bl0c0z00_80to120_lin', 'bl0c0z00_S3_80to120_binary']
    bl0c0z00_cmd = bl0c0z00_cmd.shuffle
    c00v0c00_cmd = ['c00v0c00', 'c00v0c00_90', 'c00v0c00_115', 'c00v0c00_80to120_lin', 'c00v0c00_S3_80to120_binary']
    c00v0c00_cmd = c00v0c00_cmd.shuffle
    h00g000x_cmd = ['h00g000x', 'h00g000x_90', 'h00g000x_115', 'h00g000x_80to120_lin', 'h00g000x_S3_80to120_binary']
    h00g000x_cmd = h00g000x_cmd.shuffle
    j000fac0_cmd = ['j000fac0', 'j000fac0_90', 'j000fac0_115', 'j000fac0_80to120_lin', 'j000fac0_S3_80to120_binary']
    j000fac0_cmd = j000fac0_cmd.shuffle
    cmd_shf = session[:cmd_order]
    @cmds = {cmd_shf[0] => a00wf000_cmd, cmd_shf[1] => bl0a0b00_cmd, cmd_shf[2] => bl0c0z00_cmd, cmd_shf[3] => c00v0c00_cmd, cmd_shf[4] => h00g000x_cmd, cmd_shf[5] => j000fac0_cmd}
    

  end
  
  def final_rating
    @participant = Participant.find(session[:id])
    @noten = ['Sehr Gut', 'Gut', 'Befriedigend', 'Ausreichend', 'Mangelhaft', 'Ungenuegend']
    #@noten = [1,2,3,4,5,6]
    #session[:id] = @participant[:id]
  end
  
  def end_page
    reset_session
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/rating_helper.rb
module RatingHelper

end

app/views/home/_footer.html.erb
  <div class="footer">
      Copyright 2012 | Benjamin Heinrich, Nokia | email: ext-benjamin.heinrich@nokia.com
  </div>

app/views/home/index.html.erb
    <% provide(:title, 'Start') %>

  
	<div class="header">
		<h1>
        	Audio Wahrnehmungstest
    	</h1>  
    </div>
    
	<div class="content">
  	<p1>
        <br />
        In diesem Test geht es um die Wahrnehmung von synthetisch erzeugter (computergenerierter) Sprache.<br />
        Auf den nächsten Seiten werden Sie 6 Kommandos von einem Autonavigationssystem hören. Diese werden einzeln abspielbar in 5 unterschiedlichen Varianten zu hören sein.
        Die Varianten können Sie so oft Sie wollen abspielen und gegeneinander vergleichen.
        Wählen Sie bitte bei jedem Kommando die Variante aus, welche für Sie am natürlichsten klingt. Der Inhalt der Kommandos soll nicht bewertet werden.
        <br />
        <br />
        <strong>Vorrausetzung zur Teilnahme:</strong>
          <div class="list">
	          <li>Deutsche/-r Muttersprachlerin/-sprachler bzw. Deutschkenntnisse auf muttersprachlichem Niveau</li>
	          <li>Ca. 5 Minuten Zeit</li>
	          <li>Sie haben noch nicht an dem Test teilgenommen.</li>
	          <li>Kopfhörer sind empfohlen, aber nicht zwingend nötig.</li>
	          <li>Browser: Internet Explorer 9, Firefox, Opera, Chrome und Safari (auch iOS)</li>
			  <!-- <li>Firefox wird im Moment nicht unterstützt, ist aber in Arbeit.</li> -->
          </div>
        <br />
        Abgesehen von den aufgeführten Punkten gibt es keine weiteren Anforderungen an Sie.
        Es gibt keine richtigen oder falschen Antworten. Gehen Sie von Ihrem eigenen Sprachempfinden aus.
        <br />               
        <br />         
        <strong>
          <%= link_to "Hier geht's los", rating_rating_page_path %>
        </strong>
     </p1>
	 </div>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Audio Wahrnehmungstest | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">                                          
      body {                                                         
        background-color: #124191;                                   
      	border:0.2em solid #FFFFFF;                                  
        -webkit-border-radius : 20px;                                
        -moz-border-radius : 20px;                                   
        border-radius : 20px;                                        
      	margin:3em 5em;                                              
      }                                 
   </style>
</head>
<body>
<div>
<%= yield %>

</div>

<div>

</div>

<%= render "footer"%>

</body>
</html>

app/views/participants/_footer.html.erb
  <div class="footer">
      Copyright 2012 | Benjamin Heinrich, Nokia | email: ext-benjamin.heinrich@nokia.com
  </div>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.number_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :sres1 %><br />
    <%= f.number_field :sres1 %>
  </div>
  <div class="field">
    <%= f.label :sres2 %><br />
    <%= f.number_field :res2 %>
  </div>
  <div class="field">
    <%= f.label :sres3 %><br />
    <%= f.number_field :sres3 %>
  </div>
  <div class="field">
    <%= f.label :sres4 %><br />
    <%= f.number_field :sres4 %>
  </div>
  <div class="field">
    <%= f.label :sres5 %><br />
    <%= f.number_field :sres5 %>
  </div>
  <div class="field">
    <%= f.label :sres_final %><br />
    <%= f.number_field :sres_final %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<div class="content">
<table>
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Res1</th>
    <th>Res2</th>
    <th>Res3</th>
    <th>Res4</th>
    <th>Res5</th>
    <th>Res final</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.date %></td>
    <td><%= participant.time %></td>
    <td><%= participant.sres1 %></td>
    <td><%= participant.sres2 %></td>
    <td><%= participant.sres3 %></td>
    <td><%= participant.sres4 %></td>
    <td><%= participant.sres5 %></td>
    <td><%= participant.sres_final %></td>
    <td><%= participant.comment %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, method: :delete %></td>
  </tr>
<% end %>
</table>
</div>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @participant.date %>
</p>

<p>
  <b>Time:</b>
  <%= @participant.time %>
</p>

<p>
  <b>Res1:</b>
  <%= @participant.sres1 %>
</p>

<p>
  <b>Res2:</b>
  <%= @participant.sres2 %>
</p>

<p>
  <b>Res3:</b>
  <%= @participant.sres3 %>
</p>

<p>
  <b>Res4:</b>
  <%= @participant.sres4 %>
</p>

<p>
  <b>Res5:</b>
  <%= @participant.sres5 %>
</p>

<p>
  <b>Res final:</b>
  <%= @participant.sres_final %>
</p>

<p>
  <b>Comment:</b>
  <%= @participant.comment %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/rating/_footer.html.erb
  <div class="footer">
      Copyright 2012 | Benjamin Heinrich, Nokia | email: ext-benjamin.heinrich@nokia.com
  </div>

app/views/rating/end_page.html.erb
<% provide(:title, "Ende") %>                     
                                                                                                                                                                                                                                                                                                                        
    <div class="header">                                             
      <h1>                                                           
        Vielen Dank für Ihre Teilnahme!                                  
      </h1>                                                          
    </div>

app/views/rating/final_rating.html.erb
<% provide(:title, "Fazit") %>                     
                                                                                                                                                                                                                                                                                                                        
    <div class="header">
      <h1>
        Fazit
      </h1>
    </div>
    <div class="content">
  		<p1> Wie würden Sie die Qualität der Kommandos allgemein beurteilen?</p1>
		<br />
	    <%= form_for(@participant) do |f| %>
			<% @noten.each do |note| %>
	  			<%=radio_button "participant", "sres_final", note%>
	  			<%= note%>
	  			<br />
			<% end %>
	 		<br />
	 		<p2>Kommentar:</p2>
	 		<br />
	 		<%= text_area("participant", "comment", :rows => 8, :cols => 50)%>
	    	<br />
			<%= submit_tag "Bestätigen", :confirm => "Sind Sie sicher?" %>
		<% end %>
	</div>                                                                                                

app/views/rating/rating_page.html.erb
<% provide(:title, "Kommando #{session[:cmd_nr]}") %>

	<div class="header">
      <h1>
        Kommando <%= session[:cmd_nr].to_s%>/6
      </h1>  
    </div>

    <div class="content">
    	<%i = 0%>
    	<%@cmds[session[:cmd_nr]].each do |value|%>
    		<%= @ind_titel[i]%>     	    	    	    	
    	    <%@assign[@ind_titel[i]] = value%>
    	    	<br />    	    	
    	    	<audio id="audio_<%=i%>" controls="controls" height="100" width="200" title="Variante <%= @ind_titel[i]%>">   
    	          <source src='/audio/mp3/<%=value%>.mp3' type="audio/mp3" />                             
    	          <source src='/audio/ogg/<%=value%>.ogg' type="audio/ogg" />           
    	        <embed height="100" width="100" src='/audio/mp3/<%=value%>.mp3' />
    	        </audio>
    	    <%i+=1%>
    	    <br />
    	<%end%> 
	    	                                                                                                            
    <br />
    <!-- <%=session[:cmd_order]%> -->
  	<br />
    <p1> Welche Variante empfanden Sie am natürlichsten? </p1>
    <br />

    <%= form_for(@participant) do |f| %>
    	<%first = true%>
	    <% @assign.each do |key,value| %>
			<%= radio_button "participant", "sres#{session[:cmd_nr]}", value%>
			<%if first == true%>
				<%first = false%>
			<%end%>
			<%=key%>
	    <% end %>
    	<br />
    	<%= submit_tag "Bestätigen", :confirm => "Sind Sie sicher?", :onclick => "return hasEnded()"%>
    	
    <% end %>
    
			<script>
			function hasEnded()
			  {
			  	var result = $("[id^=audio_]");
			  	var egal = result[0].ended;
			  	var x = true;
			  	for (var n = 0; n<result.length; n++) { x = x && result[n].ended; }
			  	if (x == false)		  	
			  		alert("Hören Sie sich bitte alle Varianten an!");
			  	return x
			  	
			  }
			</script>                             